### ISSUE TITLE
attempt to get length of local 'followers' (a nil value)

### ISSUE THREAD

**Issue by Pahonix** [madcowfred/wowthing_collector#5]
First, thank you for working on this. I love WoWthing!

After upgrading to 7.0.1 (and possibly it was there before that, I can't be sure), I'm getting the following error:

1x WoWthing_Collector\Collector.lua:1073: attempt to get length of local 'followers' (a nil value)
WoWthing_Collector\Collector.lua:1073: in function `ScanMissions'
WoWthing_Collector\Collector.lua:434: in function `Timer'
WoWthing_Collector\Collector.lua:459: in function <WoWthing_Collector\Collector.lua:459>
SharedXML\C_TimerAugment.lua:16: in function <SharedXML\C_TimerAugment.lua:14>

Locals:
self = <table> {
 ScanBuildings = <function> defined @WoWthing_Collector\Collector.lua:978
 ScanBag = <function> defined @WoWthing_Collector\Collector.lua:637
 ScanFollowers = <function> defined @WoWthing_Collector\Collector.lua:994
 Initialise = <function> defined @WoWthing_Collector\Collector.lua:463
 ScanPets = <function> defined @WoWthing_Collector\Collector.lua:922
 GetItemID = <function> defined @WoWthing_Collector\Collector.lua:1167
 ScanVoidStorage = <function> defined @WoWthing_Collector\Collector.lua:708
 Login = <function> defined @WoWthing_Collector\Collector.lua:505
 HookCollections = <function> defined @WoWthing_Collector\Collector.lua:858
 ParseMissionTime = <function> defined @WoWthing_Collector\Collector.lua:1181
 ScanHeirlooms = <function> defined @WoWthing_Collector\Collector.lua:889
 UpdateXP = <function> defined @WoWthing_Collector\Collector.lua:616
 UpdateExhausted = <function> defined @WoWthing_Collector\Collector.lua:624
 ScanMounts = <function> defined @WoWthing_Collector\Collector.lua:906
 Cleanup = <function> defined @WoWthing_Collector\Collector.lua:521
 GetDailyResetTime = <function> defined @WoWthing_Collector\Collector.lua:1172
 ScanToys = <function> defined @WoWthing_Collector\Collector.lua:963
 UpdateGuildBank = <function> defined @WoWthing_Collector\Collector.lua:672
 Logout = <function> defined @WoWthing_Collector\Collector.lua:516
 ScanShipments = <function> defined @WoWthing_Collector\Collector.lua:1140
 ScanReputations = <function> defined @WoWthing_Collector\Collector.lua:946
 ScanTradeSkills = <function> defined @WoWthing_Collector\Collector.lua:832
 ScanWeeklyQuests = <function> defined @WoWthing_Collector\Collector.lua:821
 ScanMissions = <function> defined @WoWthing_Collector\Collector.lua:1062
 UpdateCharacterData = <function> defined @WoWthing_Collector\Collector.lua:532
 Timer = <function> defined @WoWthing_Collector\Collector.lua:405
 ScanLockouts = <function> defined @WoWthing_Collector\Collector.lua:728
 ScanGuildBankTab = <function> defined @WoWthing_Collector\Collector.lua:682
 UpdateGuildData = <function> defined @WoWthing_Collector\Collector.lua:593
}
followerMap = <table> {
}
followers = nil
(*temporary) = 1
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to get length of local 'followers' (a nil value)"
charData = <table> {
 scanTimes = <table> {
 }
 currentXP = 0
 lastSeen = 1471141299
 flightSpeed = 310
 ships = <table> {
 }
 pets = <table> {
 }
 resting = true
 buildings = <table> {
 }
 levelXP = 657000
 followers = <table> {
 }
 garrisonLevel = 0
 bonusFaction = 1387
 playedTotal = 0
 copper = 3970242443
 lockouts = <table> {
 }
 currencies = <table> {
 }
 missions = <table> {
 }
 tradeSkills = <table> {
 }
 mounts = <table> {
 }
 reputations = <table> {
 }
 restedXP = 0
 playedLevel = 0
 items = <table> {
 }
 groundSpeed = 100
 dailyResetTime = 1471186799
 weeklyQuests = <table> {
 }
 workOrders = <table> {
 }
}
wwtc = <table> {
 ScanBuildings = <function> defined @WoWthing_Collector\Collector.lua:978
 ScanBag = <function> defined @WoWthing_Collector\Collector.lua:637
 ScanFollowers = <function> defined @WoWthing_Collector\Collector.lua:994
 Initialise = <function> defined @WoWthing_Collector\Collector.lua:463
 ScanPets = <function> defined @WoWthin

**Comment by madcowfred** [comment]
This is probably fixed for reals this time :\

**Comment by Pahonix** [comment]
Thanks very much. I'm not getting the error anymore after upgrading.
