### ISSUE TITLE
8.0.1 errors

### ISSUE THREAD

**Issue by soulyouth** [madcowfred/wowthing_collector#8]
upon logging in your get these errors 

1x WoWthing_Collector\Collector.lua:574: Attempt to register unknown event "TRADE_SKILL_UPDATE"
[C]: in function `?'
WoWthing_Collector\Collector.lua:574: in main chunk

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "TRADE_SKILL_UPDATE"

-------------
and this one 

1x WoWthing_Collector\Collector.lua:493: attempt to call method 'ScanOrderHallResearch' (a nil value)
WoWthing_Collector\Collector.lua:493: in function `?'
WoWthing_Collector\Collector.lua:569: in function <WoWthing_Collector\Collector.lua:568>

Locals:
self = <unnamed> {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = "attempt to call method 'ScanOrderHallResearch' (a nil value)"
wwtc = <table> {
}

**Comment by madcowfred** [comment]
Should all be fixed in 8.0.1.1
